### ISSUE TITLE
Is this different to the official Zabbix HTTP agent for Proxmox

### ISSUE THREAD

**Issue by andymarden** [mverboom/zabbix-pve-api#16]
That one is rather sub-par and doesn't actually create hosts since it just uses the resources part of the api. I was going to look at extending that but from what I can see your one here does the host creation etc. Is that right? Apols for creating an issue but that was the only way I could see to ask.

Happy to test and extend on my single node setup.

**Comment by andymarden** [comment]
Answered my own question - it is different and better. I can't believe that the official one is so incomplete and has the temerity to describe its use as "effortless"! If I find anything to adjust/extend, I'll do a pull request. FYI - I am operating PVE 8.0 (debian) and Zabbix 6.4, itself inside an LXC container on the host.

Nice job!

**Comment by mverboom** [comment]
I haven't tried the official one. As far as I know I started developing this template before the official one was there.
I know this template is far from complete, the problem is that in the environments I manage with proxmox, not every feature is used. For storage I mostly see zfs, so support for lvm, ceph etc. isn't something I easily test.
If you have any improvements, or suggestions (pull requests would be great :) ), don't hesitate, I appreciate constructive feedback ;)

Regards,

Mark
