### ISSUE TITLE
Template for LTS 5.0

### ISSUE THREAD

**Issue by uldiseihenbergs** [mverboom/zabbix-pve-api#4]
Hello
are the a version of the template for zabbix LTS 5.0 version?
i tried to modify existing xml by adjusting version number, but looks like zabbix changed they way how they identify items. import complains of: Invalid tag "/zabbix_export/groups/group(1)": unexpected tag "uuid".
Thanks.

**Comment by mverboom** [comment]
Hi,

I currently only have Zabbix 5.4 instances. And from what I understand it is only possible to import an exported template into the same or newer version of Zabbix..
You could try an older commit (from last year) that was made on 5.0:
https://github.com/mverboom/zabbix-pve-api/blob/9cc86619e6677f5a3f63d5484cb762a746602471/zabbix-pve-api.xml
If you can import that one and manually apply the fix in issue 2 (https://github.com/mverboom/zabbix-pve-api/issues/2)
you should have a working setup.

Let me know if this works.

Regards,

Mark

**Comment by uldiseihenbergs** [comment]
Hi, and thanks for your answer! 
i got my system working - all VMs and containers are discovered just fine.

one thing i noticed is "Memory free" item on LXC containers is not working properly, for example:
  | Memory free | 2021-06-24 11:45:03 | 483183820800 %
i checked your formula and it looks correct to me. maybe zero value is a problem? used swap for all my containers is 0B.
Thanks,
Uldis

**Comment by mverboom** [comment]
Hi,

Just took a look, formula is wrong :(
Don't have zabbix 5 to give you a fix for the old style formula. But maybe you can try yourself if I point out the issue.
The way it is calculated is:
100*((maxmem + maxswap) - (usedmed + usedswap) / (maxmem + maxswap))
The problem is the substraction isn't grouped. So the division takes place only on the used summation.
If you put parenthesis around the substraction, it should fix the problem:
 100*(((maxmem + maxswap) - (usedmed + usedswap)) / (maxmem + maxswap))

Hope I explained it correctly :)

Regards,

Mark

**Comment by uldiseihenbergs** [comment]
Thanks, that fixed it :)

**Comment by YARYKGOOD** [comment]
Hello. I have Zabbix 5.0.14 . I can't configure zabbix-pve-api. Please tell me what's wrong, tokenId how to do and how to configure? I 'm a beginner , I want to monitor virtual machines
